CREATE TABLE "commission_disputes" (
	"id" serial PRIMARY KEY NOT NULL,
	"dispute_number" text NOT NULL,
	"commission_id" integer NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"category" text NOT NULL,
	"reason" text NOT NULL,
	"expected_amount" numeric(12, 2),
	"evidence" json,
	"disputed_by" integer NOT NULL,
	"disputed_at" timestamp DEFAULT now(),
	"resolved_by" integer,
	"resolved_at" timestamp,
	"resolution" text,
	"action" text,
	"adjusted_amount" numeric(12, 2),
	"timeline" json,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "commission_disputes_dispute_number_unique" UNIQUE("dispute_number")
);
--> statement-breakpoint
CREATE TABLE "commissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_id" integer NOT NULL,
	"service_order_id" integer,
	"service_request_id" integer,
	"lead_id" integer,
	"commission_type" text DEFAULT 'service',
	"base_amount" numeric(12, 2),
	"commission_rate" numeric(6, 2),
	"commission_amount" numeric(12, 2) NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"payable_on" timestamp,
	"paid_on" timestamp,
	"payment_reference" text,
	"notes" text,
	"approved_by" integer,
	"approved_at" timestamp,
	"approval_notes" text,
	"adjusted_amount" numeric(12, 2),
	"rejected_by" integer,
	"rejected_at" timestamp,
	"rejection_reason" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
