export const CLIENT_STATUSES = {
  IN_PROGRESS: 'In Progress',
  NEEDS_ATTENTION: 'Needs Attention',
  ALMOST_DONE: 'Almost Done',
  DONE: 'Done',
} as const;

export type ClientStatus = typeof CLIENT_STATUSES[keyof typeof CLIENT_STATUSES];

const STATUS_MAP: Record<string, ClientStatus> = {
  // In Progress
  INITIATED: CLIENT_STATUSES.IN_PROGRESS,
  PENDING_PAYMENT: CLIENT_STATUSES.IN_PROGRESS,
  PAYMENT_RECEIVED: CLIENT_STATUSES.IN_PROGRESS,
  DOCUMENTS_PENDING: CLIENT_STATUSES.IN_PROGRESS,
  DOCUMENTS_UPLOADED: CLIENT_STATUSES.IN_PROGRESS,
  DOCUMENTS_VERIFIED: CLIENT_STATUSES.IN_PROGRESS,
  IN_PROGRESS: CLIENT_STATUSES.IN_PROGRESS,
  PROCESSING: CLIENT_STATUSES.IN_PROGRESS,

  // Needs Attention
  SLA_BREACHED: CLIENT_STATUSES.NEEDS_ATTENTION,
  ESCALATED: CLIENT_STATUSES.NEEDS_ATTENTION,
  ON_HOLD: CLIENT_STATUSES.NEEDS_ATTENTION,
  QC_REJECTED: CLIENT_STATUSES.NEEDS_ATTENTION,

  // Almost Done
  PENDING_REVIEW: CLIENT_STATUSES.ALMOST_DONE,
  UNDER_REVIEW: CLIENT_STATUSES.ALMOST_DONE,
  QC_REVIEW: CLIENT_STATUSES.ALMOST_DONE,
  QC_APPROVED: CLIENT_STATUSES.ALMOST_DONE,
  READY_FOR_DELIVERY: CLIENT_STATUSES.ALMOST_DONE,
  DELIVERED: CLIENT_STATUSES.ALMOST_DONE,
  AWAITING_CLIENT_CONFIRMATION: CLIENT_STATUSES.ALMOST_DONE,

  // Done
  COMPLETED: CLIENT_STATUSES.DONE,
};

export function mapToClientStatus(internalStatus: string): ClientStatus {
  return STATUS_MAP[internalStatus] || CLIENT_STATUSES.IN_PROGRESS;
}
