/**
 * Migration: Add readable ID columns to critical tables
 *
 * Adds human-readable, traceable ID columns to:
 * - service_requests (requestId: SR26...)
 * - documents (documentId: DOC26...)
 * - quality_reviews (reviewId: QC26...)
 *
 * These IDs are generated by the centralized ID generator service.
 */

import { db } from '../db';
import { sql } from 'drizzle-orm';

export async function runAddReadableIdsMigration() {
  console.log('🔄 Running add-readable-ids migration...');

  try {
    // 1. Add requestId column to service_requests
    await db.execute(sql`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name = 'service_requests' AND column_name = 'request_id'
        ) THEN
          ALTER TABLE service_requests ADD COLUMN request_id VARCHAR(20);
          CREATE UNIQUE INDEX IF NOT EXISTS idx_service_requests_request_id ON service_requests(request_id);
        END IF;
      END $$;
    `);
    console.log('  ✅ service_requests.request_id column ready');

    // 2. Add documentId column to documents table
    await db.execute(sql`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name = 'documents' AND column_name = 'document_id'
        ) THEN
          ALTER TABLE documents ADD COLUMN document_id VARCHAR(20);
          CREATE UNIQUE INDEX IF NOT EXISTS idx_documents_document_id ON documents(document_id);
        END IF;
      END $$;
    `);
    console.log('  ✅ documents.document_id column ready');

    // 3. Add reviewId column to quality_reviews
    await db.execute(sql`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name = 'quality_reviews' AND column_name = 'review_id'
        ) THEN
          ALTER TABLE quality_reviews ADD COLUMN review_id VARCHAR(20);
          CREATE UNIQUE INDEX IF NOT EXISTS idx_quality_reviews_review_id ON quality_reviews(review_id);
        END IF;
      END $$;
    `);
    console.log('  ✅ quality_reviews.review_id column ready');

    // 4. Add workItemId column to work_items if exists
    await db.execute(sql`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.tables WHERE table_name = 'work_items'
        ) AND NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name = 'work_items' AND column_name = 'work_item_id'
        ) THEN
          ALTER TABLE work_items ADD COLUMN work_item_id VARCHAR(20);
          CREATE UNIQUE INDEX IF NOT EXISTS idx_work_items_work_item_id ON work_items(work_item_id);
        END IF;
      END $$;
    `);
    console.log('  ✅ work_items.work_item_id column ready (if table exists)');

    // 5. Add workflow_instance_id column to workflow_instances if exists
    await db.execute(sql`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.tables WHERE table_name = 'workflow_instances'
        ) AND NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name = 'workflow_instances' AND column_name = 'instance_id'
        ) THEN
          ALTER TABLE workflow_instances ADD COLUMN instance_id VARCHAR(20);
          CREATE UNIQUE INDEX IF NOT EXISTS idx_workflow_instances_instance_id ON workflow_instances(instance_id);
        END IF;
      END $$;
    `);
    console.log('  ✅ workflow_instances.instance_id column ready (if table exists)');

    // 6. Add deliveryId column to delivery_confirmations
    await db.execute(sql`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM information_schema.tables WHERE table_name = 'delivery_confirmations'
        ) AND NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name = 'delivery_confirmations' AND column_name = 'delivery_id'
        ) THEN
          ALTER TABLE delivery_confirmations ADD COLUMN delivery_id VARCHAR(20);
          CREATE UNIQUE INDEX IF NOT EXISTS idx_delivery_confirmations_delivery_id ON delivery_confirmations(delivery_id);
        END IF;
      END $$;
    `);
    console.log('  ✅ delivery_confirmations.delivery_id column ready (if table exists)');

    console.log('✅ add-readable-ids migration completed successfully');
    return true;
  } catch (error) {
    console.error('❌ add-readable-ids migration failed:', error);
    return false;
  }
}

// Backfill existing records with generated IDs
export async function backfillReadableIds() {
  console.log('🔄 Backfilling existing records with readable IDs...');

  try {
    // Import ID generator functions
    const {
      generateServiceRequestId,
      generateDocumentId,
      generateQcReviewId
    } = await import('../services/id-generator');

    // 1. Backfill service_requests
    const srResult = await db.execute(sql`
      SELECT id FROM service_requests WHERE request_id IS NULL ORDER BY id
    `);

    for (const row of srResult.rows) {
      const requestId = await generateServiceRequestId();
      await db.execute(sql`
        UPDATE service_requests SET request_id = ${requestId} WHERE id = ${(row as any).id}
      `);
    }
    console.log(`  ✅ Backfilled ${srResult.rows.length} service requests`);

    // 2. Backfill documents
    const docResult = await db.execute(sql`
      SELECT id FROM documents WHERE document_id IS NULL ORDER BY id
    `);

    for (const row of docResult.rows) {
      const documentId = await generateDocumentId();
      await db.execute(sql`
        UPDATE documents SET document_id = ${documentId} WHERE id = ${(row as any).id}
      `);
    }
    console.log(`  ✅ Backfilled ${docResult.rows.length} documents`);

    // 3. Backfill quality_reviews
    const qcResult = await db.execute(sql`
      SELECT id FROM quality_reviews WHERE review_id IS NULL ORDER BY id
    `);

    for (const row of qcResult.rows) {
      const reviewId = await generateQcReviewId();
      await db.execute(sql`
        UPDATE quality_reviews SET review_id = ${reviewId} WHERE id = ${(row as any).id}
      `);
    }
    console.log(`  ✅ Backfilled ${qcResult.rows.length} quality reviews`);

    console.log('✅ Backfill completed successfully');
    return true;
  } catch (error) {
    console.error('❌ Backfill failed:', error);
    return false;
  }
}
